---

- hosts: all

  tasks:
    - name: Running sequence of commands to setup Shellinabox and change default port (4200)
      shell: |
        apt-get update
        apt-get install shellinabox
        sudo service shellinabox start
        sed -i 's/4200/{{index . 0}}/' /etc/default/shellinabox
        sudo service shellinabox restart
